import {PATHS} from '../constants';
import Head from 'next/head';

import Image from 'next/image';
import styles from '../styles/style.module.scss';
import ThemeSwitcher from '../components/ThemeSwitcher';
import Link from 'next/link';
import SocialIcons from '../components/SocialIcons';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Олег Кочиев | Сайт Портфолио</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main className={styles.main}>
        <div className={styles.themeSwitcherContainer}>
          <ThemeSwitcher />
        </div>
        <div className={styles.container}>
          <div>
            <img className={styles.logo} src="/favicon.ico" />
          </div>
          <div className={styles.vertical_line}></div>
          <div className={styles.info}>
            <h1 className={styles.my_name}>Олег Кочиев</h1>
            <div>
              <nav className={styles.navigation}>
                <Link href={PATHS.HOME()}>Главная</Link>
                <Link href={PATHS.ABOUT_ME()}>Обо мне</Link>
                <Link href={PATHS.PORTFOLIO()}>Портфолио</Link>
              </nav>
            </div>
          </div>
        </div>
        <SocialIcons />
      </main>
    </div>
  );
}
