import {PATHS} from '../constants';
import Head from 'next/head';

import Image from 'next/image';
import styles from '../styles/style.module.scss';

console.log(styles);

export default function Home() {
  return (
    <div>
      <Head>
        <title>Oleg Kochiev | Portfolio Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <img src="/favicon.ico" />
        </div>
        <div className={styles.main__verticalLine}></div>
        <div className="main__info">
          <h1>Oleg Kochiev</h1>
          <div>
            <nav>
              <a href={PATHS.HOME}>Главная</a>
              <a href={PATHS.ABOUT_ME}>Обо мне</a>
              <a href={PATHS.PORTFOLIO}>Портфолио</a>
            </nav>
            <div>
              <ul>
                <li>
                  <a href="">
                    <img src="" />
                  </a>
                </li>
                <li>
                  <a href="">
                    <img src="" />
                  </a>
                </li>
                <li>
                  <a href="">
                    <img src="" />
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </main>
      <footer></footer>
    </div>
  );
}
